name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-space:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git clone https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/mozilla-ai/README hf-space

      - run: |
          touch UPDATED_README.md
          cat HF_METADATA >> UPDATED_README.md
          echo "" >> UPDATED_README.md 
          cat profile/README.md >> UPDATED_README.md
          mv UPDATED_README.md hf-space/README.md

      - run: |
          cd hf-space
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Sync with https://github.com/mozilla-ai/.github"

      - name: Push to Hugging Face
        run: |
          cd hf-space
          git push https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/mozilla-ai/README main
